name: Build lancelot kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@v1.6.1
        with:
          kernel-url: https://github.com/aafiqbinkhayer-Toshiro/kernel_xiaomi_mt6768_hackX
          kernel-branch: genom-release
          config: lancelot_defconfig
          arch: arm64
          android-version: "11"
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
